grSim_controller_node:
  ros__parameters:
    simulator_ip: "127.0.0.1"
    simulator_port: 10301
    is_yellow_team: false
    command_topic: "robot_commands"

game_receiver_node:
  ros__parameters:
    ssl_vision_ip: "127.0.0.1"
    ssl_vision_port: 10020
    interface_ip: ""
    topic_retention: 10
    robot_topic: "robot_data"
    ball_topic: "ball_data"
    is_yellow_team: true

game_observer_node:
  ros__parameters:
    robot_amount: 3
