/**:
  ros__parameters:
    is_yellow_team: true # Color set to Yellow
    max_linear_speed: 1.0
    p_gain_linear: 1.5
    bt_xml_path: "test_tree.xml"
    execution_rate: 60.0

grSim_controller_node:
  ros__parameters:
    simulator_ip: "127.0.0.1" # Unicast IP for the simulator
    simulator_port: 10301 # Base port (will auto-switch to 10302 for Yellow)
    interface_ip: ""
    command_topic: "robot_commands"

game_receiver_node:
  ros__parameters:
    ssl_vision_ip: "224.5.23.2" # Multicast for Vision
    ssl_vision_port: 10020
    interface_ip: ""
    topic_retention: 10
    robot_topic: "robot_data"
    ball_topic: "ball_data"

gc_receiver_node:
  ros__parameters:
    referee_ip: "224.5.23.1" # Multicast for Referee
    referee_port: 10003
    interface_ip: ""
    topic_retention: 10
    gc_topic_name: "gc_data"

game_observer_node:
  ros__parameters:
    robot_amount: 3

